# Generated by Django 3.1.1 on 2020-09-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortune', models.TextField()),
                ('fortune_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='choice_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
