# Generated by Django 3.1.1 on 2020-09-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_auto_20200930_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='fortune',
            new_name='fortune_text',
        ),
    ]
