# Generated by Django 3.1.1 on 2020-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_auto_20200930_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_key',
            field=models.IntegerField(default=0),
        ),
    ]
