# Generated by Django 3.1.1 on 2020-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_question_question_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.BooleanField(default=False),
        ),
    ]
